// <auto-generated />
namespace OnlineShoppingBE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class checkForChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkForChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201912212001346_checkForChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
